#
# Copyright 2019-2022 The Z3-TurnKey Authors
# SPDX-License-Identifier: ISC
#
# Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby
# granted, provided that the above copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#

name: License Check and Multi-Platform Test

on: [ push, pull_request, workflow_dispatch ]

env:
  JDK_VERSION: 11

jobs:
  safety-check:
    name: Check for modified Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle artifacts
        uses: gradle/wrapper-validation-action@v1

  spotless:
    name: Run Spotless
    needs: safety-check
    runs-on: ubuntu-latest
    steps:
      - name: Initial Setup
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ env.JDK_VERSION }}

      - name: Run Spotless checks
        id: spotlessCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
  test:
    name: JUnit Test on ${{ matrix.os }} for ${{ matrix.jdk }} version ${{ matrix.jdk-version }}
    needs: safety-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        jdk: [ liberica, temurin, zulu ]
        jdk-version: [ 8, 11, 17 ]
      fail-fast: false # Ensure we get all failures on other platforms
    steps:
      - name: Initial Setup
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk-version }}

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test ${{ fromJSON('["-Pinstall_name_tool=true", ""]')[startsWith(matrix.os, 'macos')] }}